name: 'real world tests'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  v1:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--verbose --target universal-apple-darwin'
          - platform: 'ubuntu-20.04'
            args: '--verbose'
          - platform: 'windows-latest'
            args: '--verbose'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # node
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.x.x

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      # TODO: test the auto installation of the tauri cli
      - name: install example dependencies
        run: |
          cd ./.github/fixtures/example-v1
          pnpm install
          cd ../example-with-tauri-v1
          pnpm install

      # rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            ./.github/fixtures/example-v1/src-tauri -> ../../target
            ./.github/fixtures/example-with-tauri-v1/src-tauri -> ../../target

      # system
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

      - name: Preconfigured Tauri Project
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Updater signature is exposed here to make sure it works in PR's
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5YTBGV3JiTy9lRDZVd3NkL0RoQ1htZmExNDd3RmJaNmRMT1ZGVjczWTBKZ0FBQkFBQUFBQUFBQUFBQUlBQUFBQWdMekUzVkE4K0tWQ1hjeGt1Vkx2QnRUR3pzQjVuV0ZpM2czWXNkRm9hVUxrVnB6TUN3K1NheHJMREhQbUVWVFZRK3NIL1VsMDBHNW5ET1EzQno0UStSb21nRW4vZlpTaXIwZFh5ZmRlL1lSN0dKcHdyOUVPclVvdzFhVkxDVnZrbHM2T1o4Tk1NWEU9Cg==
        with:
          projectPath: ./.github/fixtures/example-with-tauri-v1
          includeDebug: true
          includeRelease: false
          tagName: ${{ !github.event.pull_request.head.repo.fork && 'example-with-tauri-v__VERSION__' || '' }}
          releaseName: 'Release example with preconfigured Tauri app v__VERSION__ for tauri-v1'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          args: ${{ matrix.args }}

      - name: Frontend-only Project
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Updater signature is exposed here to make sure it works in PR's
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5YTBGV3JiTy9lRDZVd3NkL0RoQ1htZmExNDd3RmJaNmRMT1ZGVjczWTBKZ0FBQkFBQUFBQUFBQUFBQUlBQUFBQWdMekUzVkE4K0tWQ1hjeGt1Vkx2QnRUR3pzQjVuV0ZpM2czWXNkRm9hVUxrVnB6TUN3K1NheHJMREhQbUVWVFZRK3NIL1VsMDBHNW5ET1EzQno0UStSb21nRW4vZlpTaXIwZFh5ZmRlL1lSN0dKcHdyOUVPclVvdzFhVkxDVnZrbHM2T1o4Tk1NWEU9Cg==
        with:
          projectPath: ./.github/fixtures/example-v1
          distPath: ../dist # relative to tauri.conf.json
          iconPath: ./icon.png # relative to projectPath
          bundleIdentifier: com.tauri.actiontest
          appName: example
          appVersion: ../package.json # relative to tauri.conf.json
          includeDebug: true
          includeRelease: false
          tagName: ${{ !github.event.pull_request.head.repo.fork && 'example-v__VERSION__' || '' }}
          releaseName: 'Release example app v__VERSION__ for tauri-v1'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          args: ${{ matrix.args }}

  v2:
    strategy:
      fail-fast: false
      matrix:
        include:
          # desktop
          - platform: 'macos-latest'
            args: '--verbose --target universal-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: '--verbose'
          - platform: 'windows-latest'
            args: '--verbose'
          # mobile
          - platform: 'ubuntu-latest'
            args: '--verbose'
            android: true
          - platform: 'macos-latest'
            args: '--verbose --debug'
            ios: true

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # node
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.x.x

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      # TODO: test the auto installation of the tauri cli
      - name: install example dependencies
        run: |
          cd ./.github/fixtures/example-v2
          pnpm install
          cd ../example-with-tauri-v2
          pnpm install

      # rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin,aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android,aarch64-apple-ios

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            ./.github/fixtures/example-v2/src-tauri -> ../../target
            ./.github/fixtures/example-with-tauri-v2/src-tauri -> ../../target

      # system
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev

      - name: Setup Java
        if: matrix.android
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        if: matrix.android
        uses: android-actions/setup-android@v3
      - name: Setup Android NDK
        if: matrix.android
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          link-to-sdk: true

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        if: matrix.ios
        with:
          xcode-version: latest-stable

      - name: init android
        if: matrix.android
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cd ./.github/fixtures/example-with-tauri-v2
          pnpm tauri android init

      - name: init ios
        if: matrix.ios
        env:
          APPLE_DEVELOPMENT_TEAM: 12345
        run: |
          cd ./.github/fixtures/example-with-tauri-v2
          pnpm tauri ios init

      - name: Preconfigured Tauri Project
        uses: ./
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          APPLE_DEVELOPMENT_TEAM: 12345
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Updater signature is exposed here to make sure it works in PR's
          TAURI_SIGNING_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5YTBGV3JiTy9lRDZVd3NkL0RoQ1htZmExNDd3RmJaNmRMT1ZGVjczWTBKZ0FBQkFBQUFBQUFBQUFBQUlBQUFBQWdMekUzVkE4K0tWQ1hjeGt1Vkx2QnRUR3pzQjVuV0ZpM2czWXNkRm9hVUxrVnB6TUN3K1NheHJMREhQbUVWVFZRK3NIL1VsMDBHNW5ET1EzQno0UStSb21nRW4vZlpTaXIwZFh5ZmRlL1lSN0dKcHdyOUVPclVvdzFhVkxDVnZrbHM2T1o4Tk1NWEU9Cg==
        with:
          projectPath: ./.github/fixtures/example-with-tauri-v2
          includeDebug: ${{ !(matrix.android || matrix.ios) }}
          includeRelease: false
          tagName: ${{ !github.event.pull_request.head.repo.fork && 'example-with-tauri-v__VERSION__' || '' }}
          releaseName: 'Release example with preconfigured Tauri app v__VERSION__ for tauri-v2'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          includeAndroid: ${{ matrix.android || false }}
          includeIOS: ${{ matrix.ios || false }}
          args: ${{ matrix.args }}

      - name: Frontend-only Project
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Updater signature is exposed here to make sure it works in PR's
          TAURI_SIGNING_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5YTBGV3JiTy9lRDZVd3NkL0RoQ1htZmExNDd3RmJaNmRMT1ZGVjczWTBKZ0FBQkFBQUFBQUFBQUFBQUlBQUFBQWdMekUzVkE4K0tWQ1hjeGt1Vkx2QnRUR3pzQjVuV0ZpM2czWXNkRm9hVUxrVnB6TUN3K1NheHJMREhQbUVWVFZRK3NIL1VsMDBHNW5ET1EzQno0UStSb21nRW4vZlpTaXIwZFh5ZmRlL1lSN0dKcHdyOUVPclVvdzFhVkxDVnZrbHM2T1o4Tk1NWEU9Cg==
        with:
          projectPath: ./.github/fixtures/example-v2
          distPath: ../dist # relative to tauri.conf.json
          iconPath: ./icon.png # relative to projectPath
          bundleIdentifier: com.tauri.actiontest
          appName: example
          appVersion: ../package.json # relative to tauri.conf.json
          includeDebug: true
          includeRelease: false
          tagName: ${{ !github.event.pull_request.head.repo.fork && 'example-v__VERSION__' || '' }}
          releaseName: 'Release example app v__VERSION__ for tauri-v2'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          args: ${{ matrix.args }}
